#!/bin/bash -e
#
# Copyright 2016, Intel Corporation
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in
#       the documentation and/or other materials provided with the
#       distribution.
#
#     * Neither the name of the copyright holder nor the names of its
#       contributors may be used to endorse or promote products derived
#       from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

export UNITTEST_NAME=file_preload/TEST0
export UNITTEST_NUM=0

# standard unit test setup
. ../unittest/unittest.sh

require_test_type short
require_build_type debug nondebug
require_fs_type any

setup

rm -f a.dump b.dump

expect_normal_exit ../../tools/mkfs.pmemfile/mkfs.pmemfile $DIR/dummy_fs 16m

mkdir -p $DIR/dummy_mount_point
mkdir -p $DIR/some_dir
ln -s ../dummy_mount_point $DIR/some_dir/some_link

export TEST_LD_PRELOAD=libpmemfile.so
export PMEMFILE_POOLS=$DIR/dummy_mount_point:$DIR/dummy_fs
export PMEMFILE_PRELOAD_LOG=pmemfile_preload.log
export INTERCEPT_LOG=intercept.log
export LIST_DIR_ON_ERROR=1
export DUMP_FILES_ON_ERROR="${INTERCEPT_LOG} ${PMEMFILE_PRELOAD_LOG}"
export UT_DUMP_LINES=1000000

expect_normal_exit ./dummy_prog$EXESUFFIX \
	$DIR/some_dir/some_link/a \
	$DIR \
	dummy_mount_point/b \
	dummy_mount_point \
	b > $DIR/root_dir.log

LD_LIBRARY_PATH=../../debug ../tools/pmemfile-cat/pmemfile-cat $DIR/dummy_fs /a > $DIR/a.dump

cmp $DIR/a.dump a.expected_dump
cmp $DIR/root_dir.log root_dir.expected_log

pass
