#!/bin/bash -e
#
# Copyright 2016-2017, Intel Corporation
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in
#       the documentation and/or other materials provided with the
#       distribution.
#
#     * Neither the name of the copyright holder nor the names of its
#       contributors may be used to endorse or promote products derived
#       from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

export UNITTEST_NAME=file_sqlite/TEST0
export UNITTEST_NUM=0

# standard unit test setup
. ../unittest/unittest.sh

require_test_type short
require_build_type debug nondebug
require_fs_type any

# XXX uncomment after rebase to master
#require_command sqlite3

setup

expect_normal_exit ../../tools/mkfs.pmemfile/mkfs.pmemfile $DIR/fs 100m

mkdir -p $DIR/mount_point

export TEST_LD_PRELOAD=libpmemfile.so
export PMEMFILE_POOLS=$DIR/mount_point:$DIR/fs
export PMEMFILE_PRELOAD_LOG=pmemfile_preload.log
export LIBC_HOOK_CMDLINE_FILTER=sqlite3
export INTERCEPT_LOG=intercept.log
export LIST_DIR_ON_ERROR=1
export DUMP_FILES_ON_ERROR="${INTERCEPT_LOG} ${PMEMFILE_PRELOAD_LOG}"
export PMEMFILE_EXIT_ON_NOT_SUPPORTED=1

expect_normal_exit sqlite3 $DIR/mount_point/sqlitedb < ins0.sql
if [ "${EXIT_BECAUSE_OF_UNSUPPORTED_FEATURE}" = "1" ]; then
	pass
	exit 0
fi

expect_normal_exit sqlite3 $DIR/mount_point/sqlitedb < sel0.sql > out0.log
if [ "${EXIT_BECAUSE_OF_UNSUPPORTED_FEATURE}" = "1" ]; then
	pass
	exit 0
fi

check

pass
